//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcuPayEntities : DbContext
    {
        public AcuPayEntities()
            : base("name=AcuPayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_1_Export_PieceWork> tbl_1_Export_PieceWork { get; set; }
        public DbSet<tbl_2_Export_TimeDetails> tbl_2_Export_TimeDetails { get; set; }
        public DbSet<tbl_3_Export_OtherEarnings> tbl_3_Export_OtherEarnings { get; set; }
        public DbSet<tbl_4_Export_SplitTime> tbl_4_Export_SplitTime { get; set; }
        public DbSet<tbl_5_Export_PieceTime> tbl_5_Export_PieceTime { get; set; }
        public DbSet<tbl_6_Export_NotRequired> tbl_6_Export_NotRequired { get; set; }
        public DbSet<tbl_Servers> tbl_Servers { get; set; }
        public DbSet<tbl_Users> tbl_Users { get; set; }
        public DbSet<tbl_Users_Servers> tbl_Users_Servers { get; set; }
        public DbSet<tbl_Estate> tbl_Estate { get; set; }
    }
}
