//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Estate
    {
        public decimal EstateID { get; set; }
        public string Guy_EstateCode { get; set; }
        public string Guy_EstateLocation { get; set; }
        public string EstateName { get; set; }
        public string AddressL1 { get; set; }
        public string AddressL2 { get; set; }
        public string AddressL3 { get; set; }
        public string Tel { get; set; }
        public string EstateExpCode { get; set; }
    }
}
