//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_1_Export_PieceWork
    {
        public decimal RecordId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal Emp_Seq_No { get; set; }
        public System.DateTime WorkDate { get; set; }
        public decimal Quantity { get; set; }
        public decimal TentativeRate { get; set; }
        public decimal TotalEarnings { get; set; }
        public decimal DayWorked { get; set; }
        public Nullable<decimal> ActivityMaster { get; set; }
        public string ActivityCode { get; set; }
        public Nullable<decimal> ExpenseCode { get; set; }
        public string Holding_ac_Code { get; set; }
        public string LocationID { get; set; }
        public string ChargedTo { get; set; }
        public string EstateLocationId { get; set; }
        public string EstateiD { get; set; }
        public Nullable<decimal> est_emp_no { get; set; }
        public string Uploaded { get; set; }
        public string TemporaryGang { get; set; }
        public string TemporaryGangOption { get; set; }
        public string Recoverable { get; set; }
        public string Unit { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
    }
}
