//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_3_Export_OtherEarnings
    {
        public decimal RecordId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal Emp_seq_no { get; set; }
        public System.DateTime Work_date { get; set; }
        public string INCOME_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> EarningRate { get; set; }
        public Nullable<decimal> Total_other_earnings { get; set; }
        public string Earnings_table_name { get; set; }
        public string Link_id { get; set; }
        public string Estate_location_id { get; set; }
        public string Estate_ID { get; set; }
        public Nullable<decimal> est_emp_no { get; set; }
        public string Uploaded { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
    }
}
