//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_6_Export_NotRequired
    {
        public decimal RecordId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<decimal> emp_seq_no { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public string NRStatus { get; set; }
        public string EstateLocationId { get; set; }
        public string EstateId { get; set; }
        public Nullable<decimal> est_emp_no { get; set; }
        public string Uploaded { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
    }
}
