//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_5_Export_PieceTime
    {
        public decimal RecordId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal Emp_seq_no { get; set; }
        public System.DateTime WorkDate { get; set; }
        public Nullable<decimal> ShiftId { get; set; }
        public System.TimeSpan FromTime { get; set; }
        public System.TimeSpan ToTime { get; set; }
        public string OverNight { get; set; }
        public string HasSplit { get; set; }
        public Nullable<System.TimeSpan> SS_FromTime { get; set; }
        public Nullable<System.TimeSpan> SS_ToTime { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> TotalEarnings { get; set; }
        public Nullable<decimal> ActivityMaster { get; set; }
        public string ActivityCode { get; set; }
        public string Holding_Acc_Code { get; set; }
        public string LocationId { get; set; }
        public string ChargedTo { get; set; }
        public string EstateLocationID { get; set; }
        public string EstateID { get; set; }
        public string TypeOfEntry { get; set; }
        public Nullable<decimal> DayWorked { get; set; }
        public Nullable<decimal> est_emp_no { get; set; }
        public string Uploaded { get; set; }
        public string Unit { get; set; }
        public string TemporaryGang { get; set; }
        public string TemporaryGangOption { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
    }
}
