//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Admin { get; set; }
    }
}
